name: haykolig
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  google_fonts: ^6.2.1
  go_router: ^14.6.1
  provider: ^6.1.2
  shared_preferences: ^2.0.15

  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  

  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
 